### ISSUE TITLE
No Callbacks when no internet connection

### ISSUE THREAD

**Issue by adamvarhegyi** [ander7agar/android-http-client#1]
Hi!

I really like your library it simple and usable. One minor thing I find that missing.
I use your lib for my apps API callings and if there's no internet connection there's no direct callback for that. E.g: I cannot inform user that he or she is not connected to world wide web. :)
I would really appreciate if you would make this little enhancement in the future.

**Comment by ander7agar** [comment]
Good idea. I might add a listener to capture this event. Thanks for the observation!
