### ISSUE TITLE
example

### ISSUE THREAD

**Issue by gsus24** [ander7agar/android-http-client#3]
Hello

try to send a curl command and failed with
`java.net.MalformedURLException: unknown protocol: org.apache.http`

This is what i would to achieve
`curl -X POST -i 'http://192.168.1.12:8090/json-rpc' --data '{"command":"componentstate","componentstate":{"component":"ALL","state":true}}'`

```
Request request = Request.create("http://192.168.1.12:8090/json-rpc");
        request.setMethod(Request.POST)
                .addHeader("command", "componentstate")
                .addParameter("component", "ALL")
                .addParameter("state", true)
```

Will this library work at all with my culr command? If so, what i am doing wrong?

**Comment by ander7agar** [comment]
Is a reformat code error in this commit https://github.com/ander7agar/android-http-client/commit/2a7da2cdb4aff4666b65b3934adde957137e9f0b.

**Comment by gsus24** [comment]
thanks for quick fix. Now i get `Error trying to perform request` caused by `HttpException: Scheme 'http' not registered.`

How it should look like for the command especially for the data body `{"command":"componentstate","componentstate":{"component":"ALL","state":true}}`?
